module.exports = {
  displayName: 'Unit Tests',
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: [
    '**/__tests__/**/*.test.ts',
    '**/*.spec.ts',
    '**/*test.ts',
    '**/test/**/*.ts',
    '!**/e2e/**',
    '!**/integration/**',
  ],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.service.ts',
    'src/**/*.controller.ts',
    'src/**/*.guard.ts',
    'src/**/*.interceptor.ts',
    'src/**/*.filter.ts',
    'src/**/*.client.ts',
    'src/**/*.registry.ts',
    'src/**/*.module.ts',
    'src/**/*.repository.ts',
    '!src/**/*.spec.ts',
    '!src/**/*.test.ts',
    '!src/**/__tests__/**',
    '!src/**/*.d.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.module.ts',
    '!src/**/index.ts',
    '!src/main.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.enum.ts',
    '!src/**/*.decorator.ts',
    '!src/**/*.constants.ts',
    '!src/**/*.config.ts',
    '!src/**/*.schema.ts',
    '!src/**/*.types.ts',
    '!src/**/*.validator.ts',
    '!src/common/decorators/**',
    '!src/config/**',
    '!src/app.module.ts',
    '!src/common/common.module.ts',
    '!src/common/services/logger.service.ts',
  ],
  coverageDirectory: 'coverage/unit',
  coverageProvider: 'v8',
  coverageReporters: ['text-summary', 'text', 'lcov', 'html'],
  verbose: true,
  forceExit: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
  },
  testTimeout: 10000,
  maxWorkers: '50%',
  bail: false,
};
