export const ANALYTICS_JOB_NAME = 'update-node';
export const NOTIFICATIONS_JOB_NAME = 'notify-result';

export const QUESTION_TYPES = {
  LIKERT: 'LIKERT',
  SINGLE_CHOICE: 'SINGLE_CHOICE',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  YES_NO: 'YES_NO',
  RUBRIC: 'RUBRIC',
  SHORT_TEXT: 'SHORT_TEXT',
  LONG_TEXT: 'LONG_TEXT',
  FILE_UPLOAD: 'FILE_UPLOAD',
  DATE: 'DATE',
  NUMERIC: 'NUMERIC',
} as const;

export const MANUAL_REVIEW_QUESTION_TYPES: ReadonlySet<string> = new Set([
  QUESTION_TYPES.SHORT_TEXT,
  QUESTION_TYPES.LONG_TEXT,
  QUESTION_TYPES.FILE_UPLOAD,
]);
