export const REPORTS_JOB_NAME = 'generate';

export const REPORT_TYPES = {
  INDIVIDUAL_RESULT: 'INDIVIDUAL_RESULT',
  CENTER_CONSOLIDADO: 'CENTER_CONSOLIDADO',
  DISTRICT_CONSOLIDADO: 'DISTRICT_CONSOLIDADO',
  REGIONAL_CONSOLIDADO: 'REGIONAL_CONSOLIDADO',
  NATIONAL_OVERVIEW: 'NATIONAL_OVERVIEW',
  PARTICIPATION_REPORT: 'PARTICIPATION_REPORT',
  PENDING_REPORT: 'PENDING_REPORT',
} as const;

export const REPORT_TYPE_VALUES = Object.values(REPORT_TYPES);

export const CLEANUP_JOB_NAME = 'cleanup-expired-reports';
export const CLEANUP_CRON_PATTERN = '0 * * * *';

export const CLASSIFICATION_FILL_COLORS: Record<string, string> = {
  Deficiente: 'FFFCA5A5',
  Regular: 'FFFDE68A',
  Bueno: 'FFBBF7D0',
  Excelente: 'FFBBF7D0',
};
